name: seamless_comm
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils=2.39=hdd6e379_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_13
  - bzip2=1.0.8=h5eee18b_6
  - c-compiler=1.2.0=h7f98852_0
  - ca-certificates=2024.11.26=h06a4308_0
  - compilers=1.2.0=ha770c72_0
  - cxx-compiler=1.2.0=h4bd325d_0
  - fortran-compiler=1.2.0=h1990efc_0
  - gcc_impl_linux-64=9.5.0=h99780fb_19
  - gcc_linux-64=9.5.0=h4258300_13
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gfortran_impl_linux-64=9.5.0=hf1096a2_19
  - gfortran_linux-64=9.5.0=hdb51d14_13
  - gxx_impl_linux-64=9.5.0=h99780fb_19
  - gxx_linux-64=9.5.0=h43f449f_13
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=9.5.0=h0a57e50_19
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libogg=1.3.5=h4ab18f5_0
  - libopus=1.3.1=h7f98852_1
  - libsanitizer=9.5.0=h2f262e1_19
  - libsndfile=1.2.2=hc60ed4a_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=9.5.0=h0a57e50_19
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - mpg123=1.32.9=hc50e24c_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.4.0=hb9d3cd8_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.8
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==24.2.0
      - audioread==3.0.1
      - bitarray==2.6.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cmake==3.31.1
      - colorama==0.4.6
      - coverage==7.6.8
      - cython==3.0.11
      - datasets==2.18.0
      - decorator==5.1.1
      - dill==0.3.8
      - exceptiongroup==1.2.2
      - fairseq2==0.2.1
      - fairseq2n==0.2.1
      - filelock==3.16.1
      - fire==0.7.0
      - flake8==7.1.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - huggingface-hub==0.26.3
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.4
      - jiwer==3.0.5
      - joblib==1.4.2
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markupsafe==3.0.2
      - mccabe==0.7.0
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.2
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai-whisper==20240930
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.3
      - pillow==11.0.0
      - pip==24.3.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pooch==1.8.2
      - portalocker==3.0.0
      - propcache==0.2.0
      - pyarrow==18.1.0
      - pyarrow-hotfix==0.6
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pytest==8.3.3
      - pytest-cov==6.0.0
      - pytest-flake8==1.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rapidfuzz==3.10.1
      - regex==2024.11.6
      - requests==2.32.3
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - setuptools==67.8.0
      - simuleval==1.1.4
      - six==1.16.0
      - sonar-space==0.2.1
      - soundfile==0.12.1
      - sox==1.5.0
      - soxr==0.5.0.post1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tbb==2021.8.0
      - tbb-devel==2021.8.0
      - tcmlib==1.2.0
      - termcolor==2.5.0
      - textgrid==1.6.1
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torcheval==0.0.7
      - tornado==6.4.2
      - tqdm
      - transformers==4.46.3
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - xxhash==3.5.0
      - yarl==1.18.0
      - yt-dlp==2024.11.18
